version: '3'
services:
  api-ponto:
    build:
      context: .
      args:
        - BUILD_CONFIGURATION=Debug
      dockerfile: Dockerfile
    image: hackathon-soat1-grp13-ponto:latest
    restart: on-failure    
    ports:
      - "5271:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=User ID=fiap;Password=SenhaLocalPonto;Host=postgres-db-ponto;Port=5432;Database=hackathonponto;Pooling=true;
    depends_on:
      postgres-db-ponto:
        condition: service_healthy

  postgres-db-ponto:  
    hostname: postgres-compose
    image: postgres
    environment:
      POSTGRES_PASSWORD: "SenhaLocalPonto"
      POSTGRES_USER: fiap
      POSTGRES_DB: hackathonponto
    ports:
      - "15437:5432"
    volumes:
      - hackathon-soat1-grp13-db-data-ponto:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  hackathon-soat1-grp13-db-data-ponto: